title: Git ja GitHub -kurssi
description: Opetusmateriaalia Gitin ja GitHubin käyttöön
baseurl: "/git-github-verkkosivut"
url: "https://purotu.github.io"

remote_theme: just-the-docs/just-the-docs

# Hakutoiminto sivuston sisällölle
search_enabled: true

# Yläpalkin/valikon väri (vaihtoehdot: https://just-the-docs.com/docs/customization/#color-schemes)
color_scheme: light

# Ylätason navigointi
nav_external_links:
  - title: Materiaalin lähdekoodi (GitHub)
    url: https://github.com/purotu/git-github-verkkosivut
    opens_in_new_tab: true

# Näytä "Muokkaa tätä sivua GitHubissa" -linkki jokaisella sivulla
gh_edit_link: true
gh_edit_link_text: "Muokkaa tätä sivua GitHubissa"
gh_edit_repository: "https://github.com/purotu/git-github-verkkosivut"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
